WebCore/Controllers/CustomTagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebCore.Controllers
{
    public class CustomTagController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebCore/Controllers/MusicAlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebCore.Services;

namespace WebCore.Controllers
{
    public class MusicAlbumController : Controller
    {
        private readonly MusicAlbumRepository musicRepository;


        public MusicAlbumController(MusicAlbumRepository musicRepository)
        {
            this.musicRepository = musicRepository;
        }

        public ViewResult Index()
        {
            return View(musicRepository.AlbumList);
        }

        public IActionResult Change()
        {
            // Cambio la data di Release degli album
            foreach (var album in this.musicRepository.AlbumList)
            {
                album.ReleaseDate = 3333;
            }

            return View("Index", musicRepository.AlbumList);
        }        
    }
}

WebCore/Controllers/UploadFileController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using WebCore.Models;
using WebCore.Services;

namespace WebCore.Controllers
{
    public class UploadFileController : Controller
    {
        private readonly IHostingEnvironment enviroment;
        private readonly ConnectionString connectionString;
        private readonly RemoteCredentials remoteCredentials;
    

        public UploadFileController(IHostingEnvironment env, IOptions<ConnectionString> connString, 
            MusicAlbumRepository musicRepository, IOptions<RemoteCredentials> remoteCredentials)
        {
            this.enviroment = env;
            this.connectionString = connString.Value;
            this.remoteCredentials = remoteCredentials.Value;


            Debug.WriteLine(connectionString.ServerInfo.IP);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Index(IFormFile file, Customer customer)
        {
            var uploads = Path.Combine(enviroment.WebRootPath, "uploads");

            using (var fs = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
            {
                await file.CopyToAsync(fs);
            }

            return View();
        }
    }
}

WebCore/Views/Shared/_Layout.cshtml
@*@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
   @* @Html.Raw(JavaScriptSnippet.FullScript)*@
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact (restrict page)</a></li>
                    <li><a asp-area="" asp-controller="UploadFile" asp-action="Index">UploadFile</a></li>
                    <li><a asp-area="" asp-controller="MusicAlbum" asp-action="Index">Music Albums</a></li>
                    <li><a asp-area="" asp-controller="CustomTag" asp-action="Index">Custom TagHelper</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="LogOut">LogOut</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - WebCore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/lodash/dist/lodash.js"></script>
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />        
        @* ReSharper disable once Html.PathError *@
        <script src="~/lib/moment/src/moment.js"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"></script>
        
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"></script>
        
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    
    @if (IsSectionDefined("Footer"))
    {
        @RenderSection("Footer")        
    }
    else
    {
        <p>Defaul Footer</p>
    }
    

@*@RenderSection("Scripts", required: false)*@
</body>
</html>